<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_lenght" value="0.325"/>
    <xacro:property name="base_width" value="0.235"/>
    <xacro:property name="base_thickness" value="0.018"/>
    <xacro:property name="wheel_radius" value="0.0825"/>
    <xacro:property name="wheel_thickness" value="0.045"/>

    <xacro:property name="bottom_wheel_offset" value="0.015"/>
    <xacro:property name="space_wheel_base" value="0.01"/>
    <xacro:property name="caster_front_offset" value="0.08"/>
    <xacro:property name="wheel_back_offset" value="0.095"/>


    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_lenght} ${base_width} ${base_thickness}"/>
            </geometry>
            <origin xyz="0 0.0 ${base_thickness/2}" rpy="0.0 0.0 0.0" />
            <material name="body_color"/>
        </visual>
        <xacro:box_inertia m="5.0" l="${base_lenght}" w="${base_width}" h="${base_thickness}"
            xyz="0 0.0 ${base_thickness/2}" rpy="0 0 0"/>
        <collision>
            <geometry>
                <box size="${base_lenght} ${base_width} ${base_thickness}"/>
            </geometry>
            <origin xyz="0 0.0 ${base_thickness/2}" rpy="0.0 0.0 0.0" />
        </collision>
    </link>

    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2.0} 0.0 0.0"/>
            <material name="wheel_color"/>
        </visual>
        <xacro:cylinder_inertia m="1.5" r="${wheel_radius}" w="${wheel_thickness}"
            xyz="0.0 0.0 0.0" rpy="${pi/2.0} 0.0 0.0"/>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2.0} 0.0 0.0"/>
        </collision>
    </link>

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
            <material name="wheel_color"/>
        </visual>
        <xacro:cylinder_inertia m="1.5" r="${wheel_radius}" w="${wheel_thickness}"
            xyz="0.0 0.0 0.0" rpy="${pi/2.0} 0.0 0.0"/>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
        </collision>
    </link>
    
    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${(bottom_wheel_offset + wheel_radius)/2}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <material name="wheel_color"/>
        </visual>
        <xacro:sphere_inertia m="0.5" r="${(bottom_wheel_offset + wheel_radius)/2}"
            xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        <collision>
            <geometry>
                <sphere radius="${(bottom_wheel_offset + wheel_radius)/2}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
    </link>

    <link name="base_foot_link">
        
    </link>


    <joint name="base_right_wheel" type="continuous">
        <origin xyz="-${base_lenght/2 - wheel_back_offset} -${base_width/2 + wheel_thickness/2 + bottom_wheel_offset} -${bottom_wheel_offset}" rpy="0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_left_wheel" type="continuous">
        <origin xyz="-${base_lenght/2 - wheel_back_offset} ${base_width/2 + wheel_thickness/2 + bottom_wheel_offset} -${bottom_wheel_offset}" rpy="0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_caster_wheel" type="fixed">
        <origin xyz="${base_lenght/2 - caster_front_offset} 0.0 -${(wheel_thickness/2 + bottom_wheel_offset)}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <axis xyz="0.0 0.0 0.0"/>
    </joint>

    <joint name="base_foo" type="fixed">
        <origin xyz="0.0 0.0 -${bottom_wheel_offset + wheel_radius}"/>
        <parent link="base_link"/>
        <child link="base_foot_link"/>
        <axis xyz="0.0 0.0 0"/>
    </joint>

</robot>